### ISSUE TITLE
install with composer

### ISSUE THREAD

**Issue by martin-git-kristensen** [sebkln/form_multistep#1]
The extension cant be find on packagist so install via composer is not possibly. Can you help me with that?

**Comment by sebkln** [comment]
Note: This extension is only a demonstration and not meant to be used in production without customization on your side. Therefore, it will not be listed on Packagist.

- If you want to use the extension in production, copy it to your TYPO3 project ([same directory as your sitepackage](https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/ExtensionInstallation/Index.html)) and require it from there.
- If you only want to give it a try, you can require the extension directly from GitHub:

        {
            "repositories": [
                {
                    "type": "vcs",
                    "url": "https://github.com/sebkln/form_multistep"
                }
            ],
            "require": {
                "sebkln/form-multistep": "dev-main",
            }
        }

See also: https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository
